repos:
-   repo: local
    hooks:
    - id: code-formatter
      name: Code Formatter
      entry: make format
      language: python
      types: [file, python]
-   repo: local
    hooks:
    - id: static-analysis
      name: Static Analysis
      entry: make lint
      language: python
      types: [file, python]
-   repo: local
    hooks:
    - id: check-for-type-hints
      name: Check for type hints
      entry: poetry run mypy .
      language: system
      types: [python]
      pass_filenames: false